"""Initial schema — incidents, anomalies, evidence, agent runs, actions, audit.

Revision ID: 2ae554c17172
Revises:
Create Date: 2026-10-06 10:18:27.078261+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=True),
        sa.Column("agent_run_id", sa.String(length=64), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("action_id", sa.String(length=64), nullable=True),
        sa.Column("approval_id", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("entry_hash"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "ix_audit_event_type_occurred", "audit_events", ["event_type", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_actor"), "audit_events", ["actor"], unique=False)
    op.create_index(
        op.f("ix_audit_events_agent_run_id"), "audit_events", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_incident_id"), "audit_events", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_incident_occurred", "audit_events", ["incident_id", "occurred_at"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column(
            "response",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_idempotency_keys_key"), "idempotency_keys", ["key"], unique=False)
    op.create_index(op.f("ix_idempotency_keys_scope"), "idempotency_keys", ["scope"], unique=False)
    op.create_index("ix_idempotency_scope_key", "idempotency_keys", ["scope", "key"], unique=True)
    op.create_table(
        "incidents",
        sa.Column("incident_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("service", sa.String(length=120), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=True),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_run_id", sa.String(length=64), nullable=True),
        sa.Column(
            "diagnosis",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("verification_outcome", sa.String(length=16), nullable=True),
        sa.Column("escalation_reason", sa.String(length=48), nullable=True),
        sa.Column("jira_issue_key", sa.String(length=64), nullable=True),
        sa.Column("slack_message_ts", sa.String(length=64), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("rollback_count", sa.Integer(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_key"),
    )
    op.create_index("ix_incidents_created_at", "incidents", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_incidents_incident_type"), "incidents", ["incident_type"], unique=False
    )
    op.create_index(op.f("ix_incidents_service"), "incidents", ["service"], unique=False)
    op.create_index(op.f("ix_incidents_severity"), "incidents", ["severity"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_index(
        "ix_incidents_status_severity_created",
        "incidents",
        ["status", "severity", "created_at"],
        unique=False,
    )
    op.create_table(
        "tool_invocations",
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("incident_id", sa.String(length=64), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column(
            "request",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "response",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=False,
    )
    op.create_index(
        op.f("ix_tool_invocations_incident_id"), "tool_invocations", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_occurred_at"), "tool_invocations", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_run_id"), "tool_invocations", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_tool_name"), "tool_invocations", ["tool_name"], unique=False
    )
    op.create_table(
        "verifications",
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("action_id", sa.String(length=64), nullable=True),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "checks",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "observed",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=False,
    )
    op.create_index(
        op.f("ix_verifications_action_id"), "verifications", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_verifications_incident_id"), "verifications", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_verifications_outcome"), "verifications", ["outcome"], unique=False)
    op.create_index(op.f("ix_verifications_run_id"), "verifications", ["run_id"], unique=False)
    op.create_table(
        "actions",
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("permission", sa.String(length=48), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("canonical_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "evidence_ids",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "expected_state",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("policy_decision", sa.String(length=24), nullable=False),
        sa.Column("policy_reason", sa.Text(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_actions_incident_id"), "actions", ["incident_id"], unique=False)
    op.create_index(
        "ix_actions_incident_status", "actions", ["incident_id", "status"], unique=False
    )
    op.create_index(op.f("ix_actions_run_id"), "actions", ["run_id"], unique=False)
    op.create_index(op.f("ix_actions_status"), "actions", ["status"], unique=False)
    op.create_index(op.f("ix_actions_tool_name"), "actions", ["tool_name"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("autonomy_level", sa.String(length=32), nullable=False),
        sa.Column("reasoner", sa.String(length=16), nullable=True),
        sa.Column("degraded_reason", sa.String(length=64), nullable=True),
        sa.Column(
            "diagnosis",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "plan",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "notes",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_incident_id"), "agent_runs", ["incident_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_state"), "agent_runs", ["state"], unique=False)
    op.create_index(
        "ix_agent_runs_state_updated", "agent_runs", ["state", "updated_at"], unique=False
    )
    op.create_table(
        "anomalies",
        sa.Column("incident_id", sa.String(length=64), nullable=True),
        sa.Column("service", sa.String(length=120), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("baseline", sa.Float(), nullable=False),
        sa.Column("observed", sa.Float(), nullable=False),
        sa.Column("deviation", sa.Float(), nullable=False),
        sa.Column("z_score", sa.Float(), nullable=False),
        sa.Column("relative_deviation", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("deduplicated", sa.Boolean(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=False,
    )
    op.create_index(op.f("ix_anomalies_dedup_key"), "anomalies", ["dedup_key"], unique=False)
    op.create_index(op.f("ix_anomalies_incident_id"), "anomalies", ["incident_id"], unique=False)
    op.create_index(op.f("ix_anomalies_metric"), "anomalies", ["metric"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column(
            "injections",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_incident_id"), "evidence", ["incident_id"], unique=False)
    op.create_index(
        "ix_evidence_incident_source", "evidence", ["incident_id", "source"], unique=False
    )
    op.create_index(op.f("ix_evidence_source"), "evidence", ["source"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=True),
        sa.Column("role", sa.String(length=24), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["actions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=False,
    )
    op.create_index(op.f("ix_approvals_action_id"), "approvals", ["action_id"], unique=False)
    op.create_index(op.f("ix_approvals_decision"), "approvals", ["decision"], unique=False)
    op.create_index(op.f("ix_approvals_incident_id"), "approvals", ["incident_id"], unique=False)
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_table(
        "run_transitions",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=24), nullable=False),
        sa.Column("to_state", sa.String(length=24), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=False,
    )
    op.create_index(
        op.f("ix_run_transitions_incident_id"), "run_transitions", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_run_transitions_occurred_at"), "run_transitions", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_run_transitions_run_id"), "run_transitions", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_transitions_run_id"), table_name="run_transitions")
    op.drop_index(op.f("ix_run_transitions_occurred_at"), table_name="run_transitions")
    op.drop_index(op.f("ix_run_transitions_incident_id"), table_name="run_transitions")
    op.drop_table("run_transitions")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_incident_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_decision"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_evidence_source"), table_name="evidence")
    op.drop_index("ix_evidence_incident_source", table_name="evidence")
    op.drop_index(op.f("ix_evidence_incident_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_anomalies_metric"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_incident_id"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_dedup_key"), table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_index("ix_agent_runs_state_updated", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_state"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_incident_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_actions_tool_name"), table_name="actions")
    op.drop_index(op.f("ix_actions_status"), table_name="actions")
    op.drop_index(op.f("ix_actions_run_id"), table_name="actions")
    op.drop_index("ix_actions_incident_status", table_name="actions")
    op.drop_index(op.f("ix_actions_incident_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_verifications_run_id"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_outcome"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_incident_id"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_action_id"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index(op.f("ix_tool_invocations_tool_name"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_run_id"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_occurred_at"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_incident_id"), table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index("ix_incidents_status_severity_created", table_name="incidents")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_severity"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_service"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_incident_type"), table_name="incidents")
    op.drop_index("ix_incidents_created_at", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_idempotency_scope_key", table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_scope"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_key"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_audit_incident_occurred", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_incident_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_agent_run_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor"), table_name="audit_events")
    op.drop_index("ix_audit_event_type_occurred", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
